{% set name = "hatch-sphinx" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/hatch_sphinx-{{ version }}.tar.gz
  sha256: a50a136fd03e337f3cfb6bcda4859131560fc29f7495cc6f60636fbc5d822d5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling !=1.32.3
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - hatchling
    - sphinx

test:
  imports:
    - hatch_sphinx
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/llimeht/hatch-sphinx
  summary: A plugin for Hatch for building documentation with Sphinx
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - backmari
    - mrakitin
